<x-layouts::admin :title="__('Platform overview')">
    <header class="flex flex-wrap items-end justify-between gap-5"><div><p class="eyebrow">The big picture</p><h1 class="display mt-3 text-4xl sm:text-5xl">Platform overview<span class="text-zinc-400">.</span></h1><p class="mt-4 text-sm text-zinc-500">Every organization. One clear view.</p></div><span class="flex items-center gap-2 text-xs text-zinc-500"><flux:icon icon="calendar-days" class="size-4"/>{{ now()->format('d M, Y') }}</span></header>
    <div class="mt-9 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">@foreach ($stats as $label => $value)<div class="panel p-6"><div class="flex items-center justify-between"><p class="text-xs text-zinc-500">{{ $label }}</p><span @class(['grid size-9 place-items-center rounded-full', 'bg-lime' => $loop->first, 'bg-zinc-100' => !$loop->first])><flux:icon :icon="['building-office-2', 'check-circle', 'users', 'sparkles'][$loop->index]" class="size-4"/></span></div><p class="display mt-5 text-4xl">{{ number_format($value) }}</p></div>@endforeach</div>
    <section class="panel mt-8 overflow-hidden"><div class="flex flex-wrap items-center justify-between gap-3 border-b border-zinc-100 p-6"><div><h2 class="text-lg font-medium tracking-tight">Registered organizations</h2><p class="mt-1 text-xs text-zinc-500">Explore workspaces and the people behind them.</p></div><span class="rounded-full bg-zinc-100 px-3 py-1.5 text-xs">{{ $organizations->total() }} results</span></div>
        <form action="{{ route('admin.dashboard') }}" method="GET" class="flex flex-col gap-3 border-b border-zinc-100 p-5 sm:flex-row sm:items-end">
            <flux:input name="search" :value="$search" label="Search organizations" placeholder="Name or workspace slug…" icon="magnifying-glass" class="sm:max-w-sm" />
            <flux:select name="status" label="Workspace status" class="sm:max-w-48"><option value="">All statuses</option><option value="active" @selected($status === 'active')>Active</option><option value="inactive" @selected($status === 'inactive')>Inactive</option></flux:select>
            <button type="submit" class="button-dark">Apply filters</button>
            @if ($search !== '' || $status !== '')<a href="{{ route('admin.dashboard') }}" class="button-outline">Clear</a>@endif
        </form>
        <div class="overflow-x-auto" tabindex="0" role="region" aria-label="Organization directory"><table class="w-full text-left text-sm"><thead class="bg-zinc-50 text-[11px] text-zinc-500"><tr><th scope="col" class="px-6 py-4 font-medium">Organization</th><th scope="col" class="px-4 py-4 font-medium">Status</th><th scope="col" class="px-4 py-4 font-medium">Members</th><th scope="col" class="px-4 py-4 font-medium">Registered</th><th scope="col" class="relative px-6 py-4"><span class="sr-only">Details</span></th></tr></thead><tbody class="divide-y divide-zinc-100">
            @forelse ($organizations as $registeredOrganization)
                <tr class="hover:bg-zinc-50/60"><td class="px-6 py-5"><div class="flex items-center gap-3"><span class="grid size-10 shrink-0 place-items-center rounded-xl bg-[#edf2e6] text-xs font-medium">{{ $registeredOrganization->initials() }}</span><div><a class="font-medium hover:underline" href="{{ route('admin.organizations.show', $registeredOrganization) }}">{{ $registeredOrganization->name }}</a><p class="mt-1 text-xs text-zinc-500">{{ $registeredOrganization->slug }}</p></div></div></td><td class="px-4 py-5"><span @class(['inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-[10px]', 'bg-green-50 text-green-800' => $registeredOrganization->is_active, 'bg-zinc-100 text-zinc-600' => !$registeredOrganization->is_active])><span class="size-1.5 rounded-full bg-current"></span>{{ $registeredOrganization->is_active ? 'Active' : 'Inactive' }}</span></td><td class="px-4 py-5">{{ $registeredOrganization->users_count }}</td><td class="px-4 py-5 text-xs whitespace-nowrap text-zinc-500">{{ $registeredOrganization->created_at?->format('d M Y') }}</td><td class="px-6 py-5"><a class="inline-flex items-center gap-2 text-xs font-medium whitespace-nowrap" href="{{ route('admin.organizations.show', $registeredOrganization) }}" aria-label="View {{ $registeredOrganization->name }}">View <span aria-hidden="true">↗</span></a></td></tr>
            @empty
                <tr><td colspan="5" class="px-5 py-16 text-center"><flux:icon icon="building-office-2" class="mx-auto size-9 text-zinc-300"/><p class="mt-4 font-medium">No organizations found</p><p class="mt-2 text-xs text-zinc-500">{{ $search || $status ? 'Try a different search or clear your filters.' : 'New workspaces will appear here when teams register.' }}</p></td></tr>
            @endforelse
        </tbody></table></div>
        @if($organizations->hasPages())<div class="border-t border-zinc-100 p-5">{{ $organizations->links() }}</div>@endif
    </section>
</x-layouts::admin>
