<x-layouts::public :title="__('One workspace for your software team')">
    <section class="mx-auto grid max-w-7xl items-center gap-12 px-5 pt-16 pb-14 sm:px-10 sm:pt-24 lg:grid-cols-[1fr_1.1fr] lg:gap-8 lg:pb-24">
        <div class="hero-copy">
            <p class="eyebrow"><span class="size-2 rounded-full bg-lime-500"></span>A clearer way to work</p>
            <h1 class="display mt-7 text-[48px] sm:text-[64px] xl:text-[76px]">Big ideas.<br>Better teamwork.<br><span class="relative inline-block">One workspace.<svg aria-hidden="true" viewBox="0 0 470 14" class="absolute -bottom-3 left-0 w-full text-lime"><path d="M3 10Q200 0 467 7" fill="none" stroke="currentColor" stroke-width="7" stroke-linecap="round"/></svg></span></h1>
            <p class="mt-9 max-w-md text-base leading-7 text-zinc-500">Give your software team a place to think clearly, stay connected, and move great work forward. Meet Startsuite.</p>
            <div class="mt-8 flex flex-wrap items-center gap-5"><a href="{{ route('register') }}" wire:navigate class="button-lime">Create your workspace <flux:icon icon="arrow-up-right" class="size-4 shrink-0" aria-hidden="true" /></a><a href="#features" class="inline-flex items-center gap-2 text-sm font-medium">Explore the product <flux:icon icon="arrow-down" class="size-4"/></a></div>
            <p class="mt-5 flex items-center gap-2 text-xs text-zinc-500"><flux:icon icon="check-circle" class="size-4"/> Your team. Your brand. Your own space.</p>
        </div>
        <div class="hero-preview">
            <x-dashboard-mockup class="lg:translate-x-2" />
        </div>
    </section>
    <div class="scroll-reveal mx-auto max-w-7xl px-5 sm:px-10"><div class="grid grid-cols-2 divide-x divide-zinc-200 rounded-xl border border-zinc-200 py-6 text-center text-sm font-medium sm:grid-cols-4"><span>Software teams</span><span>Product builders</span><span class="mt-5 sm:mt-0">Digital agencies</span><span class="mt-5 sm:mt-0">Ambitious startups</span></div></div>
    <section id="features" class="scroll-reveal mx-auto max-w-7xl scroll-mt-8 px-5 py-20 sm:px-10 sm:py-28">
        <div class="flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><div class="max-w-2xl"><p class="eyebrow">The bigger picture</p><h2 class="display mt-5 text-4xl sm:text-5xl">Everything your<br>software team needs.</h2></div><p class="max-w-sm text-sm leading-7 text-zinc-500">Plan, build, manage, and deliver from one centralized workspace. A connected home for your team, projects, workflow, and knowledge.</p></div>
        <p class="mt-8 inline-flex items-center gap-2 rounded-full bg-zinc-100 px-4 py-2 text-xs text-zinc-600"><span class="size-1.5 rounded-full bg-zinc-500"></span>Our product vision · Project tools below are coming soon</p>
        <div class="mt-7 grid gap-4 md:grid-cols-2 lg:grid-cols-3">
            @foreach ([
                ['squares-2x2', 'Smart Planner', 'Turn ideas into structured product plans in a visual workspace. Break products into categories, features, and smaller tasks, then assign the right people.', 'Plan smarter. Build with clarity.', '#f0ebff'],
                ['view-columns', 'Project Management', 'Keep work moving with flexible Kanban and Scrum boards. Assign tasks, set priorities and deadlines, and bring everyone onto the same page.', 'From backlog to done, all in one place.', '#eaf5fc'],
                ['code-bracket', 'PR & Code Review', 'Connect development to delivery. Add pull requests, assign reviewers, and follow review status from ready for review through to merged.', 'Connect your code workflow to your work.', '#eef9df'],
                ['folder', 'Project Workspace', 'Give each client or internal project a home. Keep requirements, milestones, people, tasks, documents, and development activity together.', 'Everything your project needs, in reach.', '#fff4d9'],
                ['bug-ant', 'Bug & Issue Tracking', 'Capture issues before they grow. Set priorities, assign owners, add attachments and comments, and follow every bug through to resolution.', 'Find it. Assign it. Fix it.', '#ffede6'],
                ['book-open', 'Documentation & Knowledge Base', 'Keep your team’s knowledge easy to find. Bring technical guides, requirements, project notes, and internal resources into one organized library.', 'Less searching. More shared understanding.', '#f0ebff'],
            ] as [$icon, $name, $description, $tagline, $color])
                <article class="reveal-card group rounded-2xl border border-zinc-200 p-7 transition-[transform,box-shadow,background-color] duration-300 hover:-translate-y-1 hover:bg-zinc-50 hover:shadow-[0_18px_45px_-28px_#0005]" style="--reveal-delay: {{ $loop->index * 60 }}ms"><div class="flex items-center justify-between"><span class="feature-icon grid size-12 place-items-center rounded-xl" style="background: {{ $color }}"><flux:icon :icon="$icon" class="size-6"/></span><span class="text-[10px] tracking-wider text-zinc-400 uppercase">Coming soon</span></div><h3 class="mt-6 text-xl font-medium tracking-tight">{{ $name }}</h3><p class="mt-3 text-sm leading-7 text-zinc-500">{{ $description }}</p><p class="mt-6 border-t border-zinc-100 pt-4 text-xs font-medium">{{ $tagline }}</p></article>
            @endforeach
        </div>
    </section>
    <div class="scroll-reveal mx-auto max-w-7xl px-5 sm:px-10"><div class="grid gap-8 rounded-2xl bg-zinc-950 px-8 py-10 text-white md:grid-cols-3 md:gap-0">
        @foreach ([['check', 'Less switching.', 'More time for meaningful work.', '#ffe699'], ['users', 'One shared direction.', 'A team that moves together.', '#b8f1f5'], ['sparkles', 'Space to make it yours.', 'Your people, your identity.', '#b8f66b']] as [$icon, $heading, $copy, $color])
            <div @class(['flex flex-col items-center text-center md:px-5', 'md:border-l md:border-white/15' => !$loop->first])><span class="grid h-8 w-14 place-items-center rounded-full text-zinc-950" style="background: {{ $color }}"><flux:icon :icon="$icon" class="size-4"/></span><h3 class="mt-4 text-xl font-medium tracking-tight">{{ $heading }}</h3><p class="mt-2 text-sm text-zinc-400">{{ $copy }}</p></div>
        @endforeach
    </div></div>
    <section id="how-it-works" class="scroll-reveal mx-auto mt-8 grid max-w-7xl scroll-mt-8 items-center gap-14 rounded-2xl bg-[#f7f7f5] px-5 py-16 sm:px-10 lg:grid-cols-2 lg:p-16">
        <div><p class="eyebrow">Start with your people</p><h2 class="display mt-5 text-4xl sm:text-5xl">A fresh start.<br>For your whole team.</h2><p class="mt-6 max-w-md text-sm leading-7 text-zinc-500">Your company gets a private workspace from day one. Set it up, make it yours, and give everyone a place to belong.</p><ol class="mt-8 grid gap-6">@foreach ([['Create your workspace', 'Register your company and your administrator account.'], ['Bring your identity', 'Add a logo and choose a color that feels like you.'], ['Build your team', 'Add people, assign roles, and manage their access.']] as [$heading, $copy])<li class="flex gap-4"><span class="grid size-8 shrink-0 place-items-center rounded-full border border-zinc-300 text-xs">0{{ $loop->iteration }}</span><div><h3 class="text-sm font-medium">{{ $heading }}</h3><p class="mt-1 text-sm leading-6 text-zinc-500">{{ $copy }}</p></div></li>@endforeach</ol><a href="{{ route('register') }}" wire:navigate class="button-outline mt-8">Let’s get started <flux:icon icon="arrow-up-right" class="size-4 shrink-0" aria-hidden="true" /></a></div>
        <div class="dot-grid relative px-3 py-10 sm:px-8"><div class="relative rounded-2xl border border-zinc-100 bg-white p-7 shadow-[0_20px_70px_-30px_#0003]"><div class="flex items-center justify-between"><span class="text-xs text-zinc-500">YOUR WORKSPACE</span><span class="rounded-full bg-lime px-3 py-1 text-[10px] font-medium">Ready for your team</span></div><div class="mt-7 flex items-center gap-4"><span class="grid size-14 place-items-center rounded-2xl bg-[#eee8ff] text-xl font-medium">S</span><div><h3 class="text-2xl font-medium tracking-tight">Studio North</h3><p class="mt-1 text-xs text-zinc-500">A space for our next big thing.</p></div></div><div class="mt-7 divide-y divide-zinc-100 border-t border-zinc-100">@foreach ([['AM', 'Alex Morgan', 'Super Admin', '#fff1d1'], ['JL', 'Jamie Lee', 'User', '#e4f4fa'], ['SK', 'Sam Kim', 'User', '#f0e9fd']] as [$initials, $name, $role, $color])<div class="flex items-center gap-3 py-4"><span class="grid size-9 place-items-center rounded-full text-xs" style="background: {{ $color }}">{{ $initials }}</span><span class="flex-1 text-sm">{{ $name }}</span><span class="text-[10px] text-zinc-500">{{ $role }}</span></div>@endforeach</div><p class="mt-2 text-[10px] text-zinc-400">Illustrative workspace · Your team will appear here</p></div></div>
    </section>
    <section id="workspace" class="scroll-reveal mx-auto grid max-w-7xl scroll-mt-8 items-center gap-14 px-5 py-20 sm:px-10 sm:py-28 lg:grid-cols-2">
        <div class="dot-grid order-2 flex items-center justify-center px-3 py-12 lg:order-1"><div class="w-full max-w-sm rounded-2xl border border-zinc-200 bg-white p-7 shadow-[0_20px_70px_-30px_#0003]"><p class="text-xs tracking-wider text-zinc-400 uppercase">Make yourself at home</p><h3 class="mt-4 text-2xl font-medium tracking-tight">Your team. Your style.</h3><div class="mt-7 flex gap-3">@foreach (['#b8f66b', '#b8dff6', '#cab9fc', '#ffd98b', '#f7b7ab'] as $color)<span class="grid size-10 place-items-center rounded-full" style="background: {{ $color }}">@if($loop->first)<flux:icon icon="check" class="size-5"/>@endif</span>@endforeach</div><div class="mt-8 rounded-xl bg-[#f6faef] p-5"><span class="rounded-full bg-white px-3 py-1 text-[10px]">Your identity, everywhere</span><p class="mt-5 text-xl font-medium">Hello, Studio North.</p><p class="mt-2 text-xs text-zinc-500">Looking good. Ready to make progress?</p><span class="mt-5 inline-flex rounded-lg bg-lime px-4 py-2 text-xs">Your workspace <flux:icon icon="arrow-up-right" class="inline-block size-4 shrink-0 align-text-bottom" aria-hidden="true" /></span></div></div></div>
        <div class="order-1 lg:order-2"><p class="eyebrow">Feels like your own</p><h2 class="display mt-5 text-4xl sm:text-5xl">Built around<br>your team’s identity.</h2><p class="mt-6 max-w-md text-sm leading-7 text-zinc-500">A workspace should feel like a home for your team. Personalize the details, keep access under control, and make room for what comes next.</p><ul class="mt-7 grid gap-4 text-sm">@foreach (['Your company name and logo, front and center', 'Brand colors carried through your workspace', 'Clear roles and control over team access', 'Separate organization data, by design'] as $benefit)<li class="flex gap-3"><flux:icon icon="check-circle" variant="solid" class="size-4 shrink-0"/>{{ $benefit }}</li>@endforeach</ul><a href="{{ route('register') }}" wire:navigate class="button-outline mt-8">Make it yours <flux:icon icon="arrow-up-right" class="size-4 shrink-0" aria-hidden="true" /></a></div>
    </section>
    <section id="faq" class="scroll-reveal mx-auto grid max-w-7xl scroll-mt-8 gap-10 border-t border-zinc-200 px-5 py-20 sm:px-10 lg:grid-cols-[1fr_1.3fr]"><div><p class="eyebrow">A little more clarity</p><h2 class="display mt-5 text-4xl sm:text-5xl">Good questions.<br>Clear answers.</h2></div><div class="divide-y divide-zinc-200">@foreach ([['What can I use today?', 'You can create an organization, customize its name, logo and brand color, add team members, manage roles and account access, and update your profile.'], ['Are the project tools available yet?', 'Smart Planner, project boards, PR and code review, project workspaces, issue tracking, and the knowledge base are on our roadmap. The previews show the direction we are building toward, rather than features you can use today.'], ['Who can manage my team?', 'Organization Super Admins can add and manage users, assign roles, and update organization branding. Regular users can access their workspace and manage their own profile.'], ['Can I change my branding later?', 'Yes. Organization administrators can change the company name, upload or remove a logo, and update the theme color in organization settings.'], ['Is my workspace separate from other organizations?', 'Yes. Your workspace and team data are scoped to your organization. Other organizations cannot access your team through their workspace.']] as [$question, $answer])<details class="group py-5"><summary class="flex cursor-pointer list-none items-center justify-between gap-5 text-sm font-medium">{{ $question }}<span class="grid size-7 shrink-0 place-items-center rounded-full bg-zinc-100 text-lg transition-transform duration-300 group-open:rotate-45" aria-hidden="true">+</span></summary><p class="mt-4 pr-9 text-sm leading-7 text-zinc-500">{{ $answer }}</p></details>@endforeach</div></section>
    <section class="scroll-reveal mx-3 rounded-2xl bg-lime px-5 py-16 text-center sm:mx-6 sm:py-20"><p class="eyebrow justify-center">Your next chapter starts here</p><h2 class="display mx-auto mt-5 max-w-2xl text-4xl sm:text-6xl">Great work starts<br>with a shared space.</h2><p class="mt-6 text-sm text-zinc-700">Bring your people together. Make room for your next big idea.</p><a href="{{ route('register') }}" wire:navigate class="button-dark mt-8">Create your workspace <flux:icon icon="arrow-up-right" class="size-4 shrink-0" aria-hidden="true" /></a></section>
</x-layouts::public>
